# Campaign Chemistry

Helping Advertisers Make Better Fashion Decisions

Fashion Models Photography Advertising Agencies Advertisers Photographers

## High fashion is largely driven by gut instinct 

As an advertiser, you have an exceptional influence on fashion trendsetting. As you know, the point of critical decision making occurs during the casting. You create a meaningful moment when you bring in the fashion models to meet the client, and often the designer or photographer. At this instant all the pieces of an ad campaign come together - the clothing, the model, the ad concept, and the economics. With so many complex considerations, you trust your instinct to lead to the best selection and arrangement of all of these factors. Campaign Chemistry helps you protect this valuable reputation by supplementing your instinct with quantitative analysis and insight.

## Crafting influence 

Campaign Chemistry helps you take good campaigns and make them great. Our product provides a clear portfolio optimization perspective on upcoming campaigns by predicting the estimated cost and influence of any combination of human and fashion elements available to you. 

Our analysis predicts an influence score for a hypothetical campaign by blending the components of the network (model, photographer, and brand social network connections and activity) and fashion (color, design, model, and brand relevance based on changing habits of customers). This score is then compared with a cost-to-deploy calculation (agency fees, advertising purchase costs). With these two predictive calculations, we plot the influence score vs. the cost to delivery to get an efficient frontier – most influence vs. cost for all options. This information will help decision makers make better portfolio decisions for upcoming campaigns. 

## Supporting better campaign decisions 

An eye for fashion is nearly impossible to define. However, the success of an advertising campaign may be possible to measure. Campaigns ultimately carry weight when they create influence – and influence can be approximated by revenue generation, clicks, and subsequent changes in style. Now that brands, photographers, and models have deep social networks, there is a way to better quantify influence.

We provide information at the point of decision making that you've never had before. This insight helps you gain trust in your decisions -- allowing you to pay the right price and maximize the reach of your creative genius.
